package model;
// Generated 06/06/2019 21:55:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbCustoPessoal generated by hbm2java
 */
@Entity
@Table(name="tb_custo_pessoal"
    ,catalog="meanwhile"
)
public class TbCustoPessoal  implements java.io.Serializable {


     private int idtCustoPessoal;
     private TaEvento taEvento;
     private String nmeCustoPessoal;
     private BigDecimal vlrCustoPessoal;

    public TbCustoPessoal() {
    }

    public TbCustoPessoal(int idtCustoPessoal, TaEvento taEvento, String nmeCustoPessoal, BigDecimal vlrCustoPessoal) {
       this.idtCustoPessoal = idtCustoPessoal;
       this.taEvento = taEvento;
       this.nmeCustoPessoal = nmeCustoPessoal;
       this.vlrCustoPessoal = vlrCustoPessoal;
    }
   
     @Id 

    
    @Column(name="idt_custo_pessoal", unique=true, nullable=false)
    public int getIdtCustoPessoal() {
        return this.idtCustoPessoal;
    }
    
    public void setIdtCustoPessoal(int idtCustoPessoal) {
        this.idtCustoPessoal = idtCustoPessoal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_evento", nullable=false)
    public TaEvento getTaEvento() {
        return this.taEvento;
    }
    
    public void setTaEvento(TaEvento taEvento) {
        this.taEvento = taEvento;
    }

    
    @Column(name="nme_custo_pessoal", nullable=false, length=50)
    public String getNmeCustoPessoal() {
        return this.nmeCustoPessoal;
    }
    
    public void setNmeCustoPessoal(String nmeCustoPessoal) {
        this.nmeCustoPessoal = nmeCustoPessoal;
    }

    
    @Column(name="vlr_custo_pessoal", nullable=false, precision=8)
    public BigDecimal getVlrCustoPessoal() {
        return this.vlrCustoPessoal;
    }
    
    public void setVlrCustoPessoal(BigDecimal vlrCustoPessoal) {
        this.vlrCustoPessoal = vlrCustoPessoal;
    }




}


