package model;
// Generated 06/06/2019 21:55:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbMensagem generated by hbm2java
 */
@Entity
@Table(name="tb_mensagem"
    ,catalog="meanwhile"
)
public class TbMensagem  implements java.io.Serializable {


     private Integer idtMensagem;
     private TaEvento taEvento;
     private TaParticipacao taParticipacao;
     private String dscMensagem;
     private Date dtiMensagem;

    public TbMensagem() {
    }

    public TbMensagem(TaEvento taEvento, TaParticipacao taParticipacao, String dscMensagem, Date dtiMensagem) {
       this.taEvento = taEvento;
       this.taParticipacao = taParticipacao;
       this.dscMensagem = dscMensagem;
       this.dtiMensagem = dtiMensagem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_mensagem", unique=true, nullable=false)
    public Integer getIdtMensagem() {
        return this.idtMensagem;
    }
    
    public void setIdtMensagem(Integer idtMensagem) {
        this.idtMensagem = idtMensagem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_evento", nullable=false)
    public TaEvento getTaEvento() {
        return this.taEvento;
    }
    
    public void setTaEvento(TaEvento taEvento) {
        this.taEvento = taEvento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_participacao", nullable=false)
    public TaParticipacao getTaParticipacao() {
        return this.taParticipacao;
    }
    
    public void setTaParticipacao(TaParticipacao taParticipacao) {
        this.taParticipacao = taParticipacao;
    }

    
    @Column(name="dsc_mensagem", nullable=false, length=65535)
    public String getDscMensagem() {
        return this.dscMensagem;
    }
    
    public void setDscMensagem(String dscMensagem) {
        this.dscMensagem = dscMensagem;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dti_mensagem", nullable=false, length=19)
    public Date getDtiMensagem() {
        return this.dtiMensagem;
    }
    
    public void setDtiMensagem(Date dtiMensagem) {
        this.dtiMensagem = dtiMensagem;
    }




}


