package model;
// Generated 06/06/2019 21:55:24 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbOcorrencia generated by hbm2java
 */
@Entity
@Table(name="tb_ocorrencia"
    ,catalog="meanwhile"
)
public class TbOcorrencia  implements java.io.Serializable {


     private Integer idtOcorrencia;
     private TaEvento taEvento;
     private TaParticipacao taParticipacao;
     private String dscOcorrencia;
     private Date dtiOcorrencia;

    public TbOcorrencia() {
    }

    public TbOcorrencia(TaEvento taEvento, TaParticipacao taParticipacao, String dscOcorrencia, Date dtiOcorrencia) {
       this.taEvento = taEvento;
       this.taParticipacao = taParticipacao;
       this.dscOcorrencia = dscOcorrencia;
       this.dtiOcorrencia = dtiOcorrencia;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_ocorrencia", unique=true, nullable=false)
    public Integer getIdtOcorrencia() {
        return this.idtOcorrencia;
    }
    
    public void setIdtOcorrencia(Integer idtOcorrencia) {
        this.idtOcorrencia = idtOcorrencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_evento", nullable=false)
    public TaEvento getTaEvento() {
        return this.taEvento;
    }
    
    public void setTaEvento(TaEvento taEvento) {
        this.taEvento = taEvento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_participacao", nullable=false)
    public TaParticipacao getTaParticipacao() {
        return this.taParticipacao;
    }
    
    public void setTaParticipacao(TaParticipacao taParticipacao) {
        this.taParticipacao = taParticipacao;
    }

    
    @Column(name="dsc_ocorrencia", nullable=false, length=65535)
    public String getDscOcorrencia() {
        return this.dscOcorrencia;
    }
    
    public void setDscOcorrencia(String dscOcorrencia) {
        this.dscOcorrencia = dscOcorrencia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dti_ocorrencia", nullable=false, length=19)
    public Date getDtiOcorrencia() {
        return this.dtiOcorrencia;
    }
    
    public void setDtiOcorrencia(Date dtiOcorrencia) {
        this.dtiOcorrencia = dtiOcorrencia;
    }




}


