package model;
// Generated 06/06/2019 21:55:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TbUsuario generated by hbm2java
 */
@Entity
@Table(name="tb_usuario"
    ,catalog="meanwhile"
    , uniqueConstraints = @UniqueConstraint(columnNames="eml_usuario") 
)
public class TbUsuario  implements java.io.Serializable {


     private Integer idtUsuario;
     private String nmeUsuario;
     private String emlUsuario;
     private String celUsuario;
     private String pwdUsuario;
     private Set<TaParticipacao> taParticipacaos = new HashSet<TaParticipacao>(0);
     private Set<TaEvento> taEventos = new HashSet<TaEvento>(0);

    public TbUsuario() {
    }

	
    public TbUsuario(String nmeUsuario, String emlUsuario, String celUsuario, String pwdUsuario) {
        this.nmeUsuario = nmeUsuario;
        this.emlUsuario = emlUsuario;
        this.celUsuario = celUsuario;
        this.pwdUsuario = pwdUsuario;
    }
    public TbUsuario(String nmeUsuario, String emlUsuario, String celUsuario, String pwdUsuario, Set<TaParticipacao> taParticipacaos, Set<TaEvento> taEventos) {
       this.nmeUsuario = nmeUsuario;
       this.emlUsuario = emlUsuario;
       this.celUsuario = celUsuario;
       this.pwdUsuario = pwdUsuario;
       this.taParticipacaos = taParticipacaos;
       this.taEventos = taEventos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_usuario", unique=true, nullable=false)
    public Integer getIdtUsuario() {
        return this.idtUsuario;
    }
    
    public void setIdtUsuario(Integer idtUsuario) {
        this.idtUsuario = idtUsuario;
    }

    
    @Column(name="nme_usuario", nullable=false, length=50)
    public String getNmeUsuario() {
        return this.nmeUsuario;
    }
    
    public void setNmeUsuario(String nmeUsuario) {
        this.nmeUsuario = nmeUsuario;
    }

    
    @Column(name="eml_usuario", unique=true, nullable=false, length=50)
    public String getEmlUsuario() {
        return this.emlUsuario;
    }
    
    public void setEmlUsuario(String emlUsuario) {
        this.emlUsuario = emlUsuario;
    }

    
    @Column(name="cel_usuario", nullable=false, length=20)
    public String getCelUsuario() {
        return this.celUsuario;
    }
    
    public void setCelUsuario(String celUsuario) {
        this.celUsuario = celUsuario;
    }

    
    @Column(name="pwd_usuario", nullable=false, length=16)
    public String getPwdUsuario() {
        return this.pwdUsuario;
    }
    
    public void setPwdUsuario(String pwdUsuario) {
        this.pwdUsuario = pwdUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbUsuario")
    public Set<TaParticipacao> getTaParticipacaos() {
        return this.taParticipacaos;
    }
    
    public void setTaParticipacaos(Set<TaParticipacao> taParticipacaos) {
        this.taParticipacaos = taParticipacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbUsuario")
    public Set<TaEvento> getTaEventos() {
        return this.taEventos;
    }
    
    public void setTaEventos(Set<TaEvento> taEventos) {
        this.taEventos = taEventos;
    }




}


