package model;
// Generated 06/06/2019 21:55:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TdTipoEvento generated by hbm2java
 */
@Entity
@Table(name="td_tipo_evento"
    ,catalog="meanwhile"
    , uniqueConstraints = @UniqueConstraint(columnNames="nme_tipo_evento") 
)
public class TdTipoEvento  implements java.io.Serializable {


     private Integer idtTipoEvento;
     private String nmeTipoEvento;
     private Set<TaEvento> taEventos = new HashSet<TaEvento>(0);

    public TdTipoEvento() {
    }

	
    public TdTipoEvento(String nmeTipoEvento) {
        this.nmeTipoEvento = nmeTipoEvento;
    }
    public TdTipoEvento(String nmeTipoEvento, Set<TaEvento> taEventos) {
       this.nmeTipoEvento = nmeTipoEvento;
       this.taEventos = taEventos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_tipo_evento", unique=true, nullable=false)
    public Integer getIdtTipoEvento() {
        return this.idtTipoEvento;
    }
    
    public void setIdtTipoEvento(Integer idtTipoEvento) {
        this.idtTipoEvento = idtTipoEvento;
    }

    
    @Column(name="nme_tipo_evento", unique=true, nullable=false, length=50)
    public String getNmeTipoEvento() {
        return this.nmeTipoEvento;
    }
    
    public void setNmeTipoEvento(String nmeTipoEvento) {
        this.nmeTipoEvento = nmeTipoEvento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdTipoEvento")
    public Set<TaEvento> getTaEventos() {
        return this.taEventos;
    }
    
    public void setTaEventos(Set<TaEvento> taEventos) {
        this.taEventos = taEventos;
    }




}


