# Generated by Django 3.2.3 on 2021-05-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
